# use java support
language: java
jdk:
  - openjdk11

# run in container
sudo: false

# use linux as operating system
os:
  - linux

addons:
  apt:
    packages:
      - s3cmd

# run maven build
script:
  - ./gradlew clean build

cache:
  directories:
    - $HOME/.gradle/caches/

# Deploy snapshots on every commit made to master branch
# Deploy releases on every tag push
deploy:
  - provider: script
    script: ./gradlew publish -PrepositoryUrl=$mavenPublishURL/public-snapshots/ -PrepositoryUsername=$mavenPublishUsername -PrepositoryPassword=$mavenPublishPassword
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: bash .ci/release.sh
    skip_cleanup: true
    on:
      tags: true

